/*  =========================================================================
    czguide_classes - private header file

    Copyright (c) the Authors
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef CZGUIDE_CLASSES_H_INCLUDED
#define CZGUIDE_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/czguide.h"

//  Extra headers

//  Opaque class structures to allow forward references

//  Internal API


//  *** To avoid double-definitions, only define if building without draft ***
#ifndef CZGUIDE_BUILD_DRAFT_API

//  Self test for private classes
CZGUIDE_PRIVATE void
    czguide_private_selftest (bool verbose);

#endif // CZGUIDE_BUILD_DRAFT_API

#endif
